// ═══════════════════════════════════════════════════════════════
// SARANG LIVING — Product Data (Static, pre-Module 2)
// 77 usable SKUs from Sarang.pdf · SL063 & SL064 excluded
// ═══════════════════════════════════════════════════════════════

export interface Product {
  sku: string;
  name: string;
  slug: string;
  price: number;
  compareAtPrice?: number;
  category: string;
  parentCategory: string;
  description: string;
  images: string[];
  stockQuantity: number;
  isActive: boolean;
}

export interface Category {
  name: string;
  slug: string;
  parentCategory: string;
  productCount: number;
  description: string;
}

// ─── Categories ───
export const categories: Category[] = [
  {
    name: 'Claw Clips',
    slug: 'claw-clips',
    parentCategory: 'Hair Accessories',
    productCount: 17,
    description: 'From delicate mini clips to bold statement pieces — find the perfect claw clip for every hair moment.',
  },
  {
    name: 'Scrunchies',
    slug: 'scrunchies',
    parentCategory: 'Hair Accessories',
    productCount: 10,
    description: 'Soft, stylish scrunchies in velvet, satin, pearl, and plaid — gentle on your hair, gorgeous on your wrist.',
  },
  {
    name: 'Snap & Barrette Clips',
    slug: 'snap-barrette-clips',
    parentCategory: 'Hair Accessories',
    productCount: 11,
    description: 'Elegant snaps and barrettes — from pearl details to rhinestone sparkle.',
  },
  {
    name: 'Bows',
    slug: 'bows',
    parentCategory: 'Hair Accessories',
    productCount: 8,
    description: 'Ribbon bows, rhinestone bows, striped bows — add a touch of sweetness to any look.',
  },
  {
    name: 'Headbands',
    slug: 'headbands',
    parentCategory: 'Hair Accessories',
    productCount: 7,
    description: 'Padded, beaded, floral — headbands that elevate your everyday to editorial.',
  },
  {
    name: 'Kids & Novelty Sets',
    slug: 'kids-novelty-sets',
    parentCategory: 'Hair Accessories',
    productCount: 6,
    description: 'Playful clip sets with cartoon characters and colorful designs — perfect for little ones.',
  },
  {
    name: 'Ties & Elastics',
    slug: 'ties-elastics',
    parentCategory: 'Hair Accessories',
    productCount: 5,
    description: 'Hair ties, telephone cord rings, and elastic packs — essentials with a Sarang twist.',
  },
  {
    name: 'Duck & Alligator Clips',
    slug: 'duck-alligator-clips',
    parentCategory: 'Hair Accessories',
    productCount: 4,
    description: 'Acetate, matte, and floral duck clips — the styling tool that doubles as an accessory.',
  },
  {
    name: 'Pins & Forks',
    slug: 'pins-forks',
    parentCategory: 'Hair Accessories',
    productCount: 1,
    description: 'Elegant hair forks and pins for effortless updos.',
  },
  {
    name: 'Nails',
    slug: 'nails',
    parentCategory: 'Nails',
    productCount: 2,
    description: 'Salon-quality press-on nails — instant glam, zero damage.',
  },
];

// ─── Products ───
export const products: Product[] = [
  {
    sku: 'SL001',
    name: 'Press-on Nails',
    slug: 'press-on-nails-sl001',
    price: 120,
    category: 'Nails',
    parentCategory: 'Nails',
    description: 'Salon-quality press-on nails for instant glam. Easy to apply, gentle to remove, and designed to make your nails look effortlessly gorgeous.',
    images: [],
    stockQuantity: 25,
    isActive: true,
  },
  {
    sku: 'SL002',
    name: 'Patterned Scrunchie',
    slug: 'patterned-scrunchie-sl002',
    price: 50,
    category: 'Scrunchies',
    parentCategory: 'Hair Accessories',
    description: 'A beautifully patterned scrunchie that adds a pop of personality to your ponytail. Soft, stretchy, and kind to your hair.',
    images: [],
    stockQuantity: 40,
    isActive: true,
  },
  {
    sku: 'SL003',
    name: 'Hair Bow / Bow Clip',
    slug: 'hair-bow-clip-sl003',
    price: 137,
    category: 'Bows',
    parentCategory: 'Hair Accessories',
    description: 'A classic hair bow clip that brings a touch of elegance to any hairstyle. Perfect for everyday wear or special occasions.',
    images: [],
    stockQuantity: 30,
    isActive: true,
  },
  {
    sku: 'SL004',
    name: 'Butterfly Hair Elastic / Ponytail Holder',
    slug: 'butterfly-hair-elastic-sl004',
    price: 330,
    category: 'Ties & Elastics',
    parentCategory: 'Hair Accessories',
    description: 'An enchanting butterfly-shaped hair elastic that transforms a simple ponytail into something magical. Premium quality with a secure hold.',
    images: [],
    stockQuantity: 15,
    isActive: true,
  },
  {
    sku: 'SL005',
    name: 'Hair Fork / Hair Pin',
    slug: 'hair-fork-pin-sl005',
    price: 330,
    category: 'Pins & Forks',
    parentCategory: 'Hair Accessories',
    description: 'An elegant hair fork that effortlessly holds updos and twisted styles in place. Minimalist design, maximum sophistication.',
    images: [],
    stockQuantity: 20,
    isActive: true,
  },
  {
    sku: 'SL006',
    name: 'Rhinestone Bow Clip',
    slug: 'rhinestone-bow-clip-sl006',
    price: 250,
    category: 'Bows',
    parentCategory: 'Hair Accessories',
    description: 'A stunning bow clip adorned with sparkling rhinestones. Perfect for adding a touch of luxury to your look.',
    images: [],
    stockQuantity: 18,
    isActive: true,
  },
  {
    sku: 'SL007',
    name: 'Rhinestone Bow Clip',
    slug: 'rhinestone-bow-clip-sl007',
    price: 200,
    category: 'Bows',
    parentCategory: 'Hair Accessories',
    description: 'A dazzling rhinestone bow clip in a delicate design. Catches the light beautifully for day-to-night versatility.',
    images: [],
    stockQuantity: 22,
    isActive: true,
  },
  {
    sku: 'SL008',
    name: 'Butterfly Claw Clip',
    slug: 'butterfly-claw-clip-sl008',
    price: 240,
    category: 'Claw Clips',
    parentCategory: 'Hair Accessories',
    description: 'A graceful butterfly-shaped claw clip that holds your hair securely while looking absolutely beautiful.',
    images: [],
    stockQuantity: 20,
    isActive: true,
  },
  {
    sku: 'SL009',
    name: 'Mini Claw Clip Set',
    slug: 'mini-claw-clip-set-sl009',
    price: 10,
    category: 'Claw Clips',
    parentCategory: 'Hair Accessories',
    description: 'A set of adorable mini claw clips — perfect for half-up styles, sectioning, or adding tiny details to any look.',
    images: [],
    stockQuantity: 50,
    isActive: true,
  },
  {
    sku: 'SL010',
    name: 'Velvet Scrunchie Set',
    slug: 'velvet-scrunchie-set-sl010',
    price: 60,
    category: 'Scrunchies',
    parentCategory: 'Hair Accessories',
    description: 'Luxuriously soft velvet scrunchies in a curated set. The rich texture adds a touch of indulgence to your everyday hair routine.',
    images: [],
    stockQuantity: 35,
    isActive: true,
  },
  {
    sku: 'SL011',
    name: 'Fabric Scrunchie',
    slug: 'fabric-scrunchie-sl011',
    price: 120,
    category: 'Scrunchies',
    parentCategory: 'Hair Accessories',
    description: 'A beautifully crafted fabric scrunchie with premium stitching and a generous size that makes any updo look effortlessly chic.',
    images: [],
    stockQuantity: 30,
    isActive: true,
  },
  {
    sku: 'SL012',
    name: 'Spiral Hair Tie / Telephone Cord Hair Ring',
    slug: 'spiral-hair-tie-sl012',
    price: 100,
    category: 'Ties & Elastics',
    parentCategory: 'Hair Accessories',
    description: 'No-crease spiral hair ties that grip without pulling. Fun, functional, and gentle on all hair types.',
    images: [],
    stockQuantity: 40,
    isActive: true,
  },
  {
    sku: 'SL013',
    name: 'Flower Claw Clip',
    slug: 'flower-claw-clip-sl013',
    price: 100,
    category: 'Claw Clips',
    parentCategory: 'Hair Accessories',
    description: 'A charming flower-shaped claw clip that brings garden-fresh beauty to your hairstyle.',
    images: [],
    stockQuantity: 28,
    isActive: true,
  },
  {
    sku: 'SL014',
    name: 'Flower Claw Clip Set',
    slug: 'flower-claw-clip-set-sl014',
    price: 100,
    category: 'Claw Clips',
    parentCategory: 'Hair Accessories',
    description: 'A coordinated set of flower claw clips in complementary colors. Mix, match, and bloom.',
    images: [],
    stockQuantity: 25,
    isActive: true,
  },
  {
    sku: 'SL015',
    name: 'Hair Bow / Bow Clip',
    slug: 'hair-bow-clip-sl015',
    price: 270,
    category: 'Bows',
    parentCategory: 'Hair Accessories',
    description: 'A statement hair bow clip with a larger silhouette — for those days when you want to make an impression.',
    images: [],
    stockQuantity: 15,
    isActive: true,
  },
  {
    sku: 'SL016',
    name: 'Fabric Bow Claw Clip',
    slug: 'fabric-bow-claw-clip-sl016',
    price: 220,
    category: 'Claw Clips',
    parentCategory: 'Hair Accessories',
    description: 'The best of both worlds: a claw clip topped with a soft fabric bow. Secure hold meets irresistible charm.',
    images: [],
    stockQuantity: 20,
    isActive: true,
  },
  {
    sku: 'SL017',
    name: 'Hair Bow / Bow Clip',
    slug: 'hair-bow-clip-sl017',
    price: 135,
    category: 'Bows',
    parentCategory: 'Hair Accessories',
    description: 'A dainty bow clip in a versatile size — slides right into place and stays put all day long.',
    images: [],
    stockQuantity: 32,
    isActive: true,
  },
  {
    sku: 'SL018',
    name: 'Headband / Tiara',
    slug: 'headband-tiara-sl018',
    price: 225,
    category: 'Headbands',
    parentCategory: 'Hair Accessories',
    description: 'A headband with tiara-like detailing — because every day deserves a little crown energy.',
    images: [],
    stockQuantity: 12,
    isActive: true,
  },
  {
    sku: 'SL019',
    name: 'Flower Hair Clip / Ribbon Flower Clip',
    slug: 'flower-ribbon-clip-sl019',
    price: 150,
    category: 'Snap & Barrette Clips',
    parentCategory: 'Hair Accessories',
    description: 'A delicate ribbon flower clip that adds a romantic, garden-party feel to your hairstyle.',
    images: [],
    stockQuantity: 25,
    isActive: true,
  },
  {
    sku: 'SL020',
    name: 'Pearl Scrunchie',
    slug: 'pearl-scrunchie-sl020',
    price: 150,
    category: 'Scrunchies',
    parentCategory: 'Hair Accessories',
    description: 'A scrunchie embellished with delicate pearl details — elevated simplicity for your ponytail or bun.',
    images: [],
    stockQuantity: 20,
    isActive: true,
  },
  {
    sku: 'SL021',
    name: 'Faux Fur Scrunchie',
    slug: 'faux-fur-scrunchie-sl021',
    price: 60,
    category: 'Scrunchies',
    parentCategory: 'Hair Accessories',
    description: 'Plush faux fur scrunchie that feels as cozy as it looks. A winter-to-spring staple for textured updos.',
    images: [],
    stockQuantity: 35,
    isActive: true,
  },
  {
    sku: 'SL022',
    name: 'Banana Clip',
    slug: 'banana-clip-sl022',
    price: 30,
    category: 'Claw Clips',
    parentCategory: 'Hair Accessories',
    description: 'A classic banana clip for effortless volume and hold. Simple, effective, timeless.',
    images: [],
    stockQuantity: 45,
    isActive: true,
  },
  {
    sku: 'SL023',
    name: 'Banana Clip',
    slug: 'banana-clip-sl023',
    price: 20,
    category: 'Claw Clips',
    parentCategory: 'Hair Accessories',
    description: 'A lightweight banana clip in a compact design — great for quick updos and everyday styling.',
    images: [],
    stockQuantity: 50,
    isActive: true,
  },
  {
    sku: 'SL024',
    name: 'Rhinestone Tassel Hair Clip',
    slug: 'rhinestone-tassel-clip-sl024',
    price: 405,
    category: 'Snap & Barrette Clips',
    parentCategory: 'Hair Accessories',
    description: 'A show-stopping rhinestone clip with dangling tassel accents. For when your hair deserves jewelry.',
    images: [],
    stockQuantity: 10,
    isActive: true,
  },
  {
    sku: 'SL025',
    name: 'Elastic Hair Band / Hair Rubbers Pack',
    slug: 'elastic-hair-band-pack-sl025',
    price: 100,
    category: 'Ties & Elastics',
    parentCategory: 'Hair Accessories',
    description: 'A generous pack of elastic hair bands — the everyday essentials, curated with care.',
    images: [],
    stockQuantity: 60,
    isActive: true,
  },
  {
    sku: 'SL026',
    name: 'Lace Flower Hair Clip',
    slug: 'lace-flower-clip-sl026',
    price: 120,
    category: 'Snap & Barrette Clips',
    parentCategory: 'Hair Accessories',
    description: 'A romantic lace flower clip that brings vintage charm to modern hairstyles.',
    images: [],
    stockQuantity: 22,
    isActive: true,
  },
  {
    sku: 'SL027',
    name: 'Ribbon Flower Hair Clip',
    slug: 'ribbon-flower-clip-sl027',
    price: 120,
    category: 'Snap & Barrette Clips',
    parentCategory: 'Hair Accessories',
    description: 'A handcrafted ribbon flower clip — soft, feminine, and perfect for adding a delicate accent.',
    images: [],
    stockQuantity: 28,
    isActive: true,
  },
  {
    sku: 'SL028',
    name: 'Ribbon Flower Hair Clip',
    slug: 'ribbon-flower-clip-sl028',
    price: 150,
    category: 'Snap & Barrette Clips',
    parentCategory: 'Hair Accessories',
    description: 'An elevated ribbon flower clip with premium detailing and a generous bloom that catches every eye.',
    images: [],
    stockQuantity: 20,
    isActive: true,
  },
  {
    sku: 'SL029',
    name: 'Faux Fur Hair Tie / Scrunchie Set',
    slug: 'faux-fur-scrunchie-set-sl029',
    price: 135,
    category: 'Scrunchies',
    parentCategory: 'Hair Accessories',
    description: 'A curated set of faux fur scrunchies — texture, warmth, and style bundled together.',
    images: [],
    stockQuantity: 18,
    isActive: true,
  },
  {
    sku: 'SL030',
    name: 'Spa Headband & Wristband Set',
    slug: 'spa-headband-wristband-set-sl030',
    price: 200,
    category: 'Headbands',
    parentCategory: 'Hair Accessories',
    description: 'The ultimate self-care accessory set. Keep your hair back and your wrists dry during skincare routines.',
    images: [],
    stockQuantity: 20,
    isActive: true,
  },
  {
    sku: 'SL031',
    name: 'Bubble Padded Headband & Wristband Set',
    slug: 'bubble-padded-headband-set-sl031',
    price: 250,
    category: 'Headbands',
    parentCategory: 'Hair Accessories',
    description: 'A plush, bubble-padded headband with matching wristbands — adorable for skincare routines and beyond.',
    images: [],
    stockQuantity: 15,
    isActive: true,
  },
  {
    sku: 'SL032',
    name: 'Bubble Padded Headband & Wristband Set',
    slug: 'bubble-padded-headband-set-sl032',
    price: 250,
    category: 'Headbands',
    parentCategory: 'Hair Accessories',
    description: 'Another colorway of our popular bubble padded set — same cozy comfort, different aesthetic mood.',
    images: [],
    stockQuantity: 15,
    isActive: true,
  },
  {
    sku: 'SL033',
    name: 'Duck Clip / Alligator Hair Clip',
    slug: 'duck-clip-sl033',
    price: 113,
    category: 'Duck & Alligator Clips',
    parentCategory: 'Hair Accessories',
    description: 'A sleek duck clip for precise styling and sectioning. Professional quality, everyday elegance.',
    images: [],
    stockQuantity: 30,
    isActive: true,
  },
  {
    sku: 'SL034',
    name: 'Snap Hair Clip Set',
    slug: 'snap-hair-clip-set-sl034',
    price: 140,
    category: 'Snap & Barrette Clips',
    parentCategory: 'Hair Accessories',
    description: 'A coordinated set of snap clips — mix and match for endless styling possibilities.',
    images: [],
    stockQuantity: 25,
    isActive: true,
  },
  {
    sku: 'SL035',
    name: 'Cartoon Hair Clip Set',
    slug: 'cartoon-hair-clip-set-sl035',
    price: 120,
    category: 'Kids & Novelty Sets',
    parentCategory: 'Hair Accessories',
    description: 'Playful cartoon-themed clips that bring smiles to little faces. Fun, colorful, and perfectly sized for kids.',
    images: [],
    stockQuantity: 35,
    isActive: true,
  },
  {
    sku: 'SL036',
    name: 'Snap Hair Clip / Pom-Pom Clip',
    slug: 'pom-pom-snap-clip-sl036',
    price: 50,
    category: 'Snap & Barrette Clips',
    parentCategory: 'Hair Accessories',
    description: 'A cheerful pom-pom snap clip that adds a playful, tactile accent to any hairstyle.',
    images: [],
    stockQuantity: 40,
    isActive: true,
  },
  {
    sku: 'SL037',
    name: 'Plush Furry Hair Clip',
    slug: 'plush-furry-clip-sl037',
    price: 60,
    category: 'Snap & Barrette Clips',
    parentCategory: 'Hair Accessories',
    description: 'A soft, furry clip that adds irresistible texture to your look. Touch it once and you won\'t want to let go.',
    images: [],
    stockQuantity: 30,
    isActive: true,
  },
  {
    sku: 'SL038',
    name: 'Cartoon Hair Clip Set',
    slug: 'cartoon-hair-clip-set-sl038',
    price: 140,
    category: 'Kids & Novelty Sets',
    parentCategory: 'Hair Accessories',
    description: 'A deluxe cartoon clip set with more designs and characters — the ultimate gift for clip-loving kids.',
    images: [],
    stockQuantity: 28,
    isActive: true,
  },
  {
    sku: 'SL039',
    name: 'Plaid Scrunchie',
    slug: 'plaid-scrunchie-sl039',
    price: 68,
    category: 'Scrunchies',
    parentCategory: 'Hair Accessories',
    description: 'A preppy plaid scrunchie that channels classic academia style. Perfect for autumn looks.',
    images: [],
    stockQuantity: 30,
    isActive: true,
  },
  {
    sku: 'SL040',
    name: 'Satin Scrunchie',
    slug: 'satin-scrunchie-sl040',
    price: 70,
    category: 'Scrunchies',
    parentCategory: 'Hair Accessories',
    description: 'A silky satin scrunchie that reduces friction and frizz while looking effortlessly luxe.',
    images: [],
    stockQuantity: 35,
    isActive: true,
  },
  {
    sku: 'SL041',
    name: 'Butterfly Hair Clip',
    slug: 'butterfly-hair-clip-sl041',
    price: 70,
    category: 'Snap & Barrette Clips',
    parentCategory: 'Hair Accessories',
    description: 'A delicate butterfly clip that adds a whisper of whimsy to your hair.',
    images: [],
    stockQuantity: 35,
    isActive: true,
  },
  {
    sku: 'SL042',
    name: 'Houndstooth Pearl Scrunchie',
    slug: 'houndstooth-pearl-scrunchie-sl042',
    price: 70,
    category: 'Scrunchies',
    parentCategory: 'Hair Accessories',
    description: 'Classic houndstooth pattern meets pearl embellishment — a scrunchie that means business and beauty.',
    images: [],
    stockQuantity: 25,
    isActive: true,
  },
  {
    sku: 'SL043',
    name: 'Satin Scrunchie',
    slug: 'satin-scrunchie-sl043',
    price: 45,
    category: 'Scrunchies',
    parentCategory: 'Hair Accessories',
    description: 'A lightweight satin scrunchie at an irresistible price. Stock up on this everyday essential.',
    images: [],
    stockQuantity: 50,
    isActive: true,
  },
  {
    sku: 'SL044',
    name: 'Acetate Duck Clip / Alligator Clip',
    slug: 'acetate-duck-clip-sl044',
    price: 140,
    category: 'Duck & Alligator Clips',
    parentCategory: 'Hair Accessories',
    description: 'A premium acetate duck clip with a tortoiseshell-inspired finish. Lightweight, strong, and sophisticated.',
    images: [],
    stockQuantity: 22,
    isActive: true,
  },
  {
    sku: 'SL045',
    name: 'Cartoon Character Hair Clip Set',
    slug: 'cartoon-character-clip-set-sl045',
    price: 120,
    category: 'Kids & Novelty Sets',
    parentCategory: 'Hair Accessories',
    description: 'Beloved cartoon characters on cute little clips. A guaranteed hit with kids of all ages.',
    images: [],
    stockQuantity: 30,
    isActive: true,
  },
  {
    sku: 'SL046',
    name: 'Kids Hair Clip Set',
    slug: 'kids-hair-clip-set-sl046',
    price: 120,
    category: 'Kids & Novelty Sets',
    parentCategory: 'Hair Accessories',
    description: 'A colorful assortment of kids\' clips designed to make getting ready fun and fuss-free.',
    images: [],
    stockQuantity: 30,
    isActive: true,
  },
  {
    sku: 'SL047',
    name: 'Kids Hair Clip Set',
    slug: 'kids-hair-clip-set-sl047',
    price: 120,
    category: 'Kids & Novelty Sets',
    parentCategory: 'Hair Accessories',
    description: 'Another edition of our popular kids\' clip set — different designs, same quality and cuteness.',
    images: [],
    stockQuantity: 30,
    isActive: true,
  },
  {
    sku: 'SL048',
    name: 'Mini Claw Clip Set',
    slug: 'mini-claw-clip-set-sl048',
    price: 50,
    category: 'Claw Clips',
    parentCategory: 'Hair Accessories',
    description: 'A collection of mini claw clips in assorted colors — tiny but mighty for half-up looks.',
    images: [],
    stockQuantity: 40,
    isActive: true,
  },
  {
    sku: 'SL049',
    name: 'Metal Claw Clip',
    slug: 'metal-claw-clip-sl049',
    price: 90,
    category: 'Claw Clips',
    parentCategory: 'Hair Accessories',
    description: 'A sleek metal claw clip with a cool, industrial-minimalist edge. Strong grip, modern look.',
    images: [],
    stockQuantity: 25,
    isActive: true,
  },
  {
    sku: 'SL050',
    name: 'Flower Claw Clip',
    slug: 'flower-claw-clip-sl050',
    price: 25,
    category: 'Claw Clips',
    parentCategory: 'Hair Accessories',
    description: 'A petite flower claw clip at an everyday price — sweet, simple, and endlessly wearable.',
    images: [],
    stockQuantity: 50,
    isActive: true,
  },
  {
    sku: 'SL051',
    name: 'Pearl Detail Hair Elastic',
    slug: 'pearl-detail-elastic-sl051',
    price: 10,
    category: 'Ties & Elastics',
    parentCategory: 'Hair Accessories',
    description: 'A simple hair elastic elevated with a tiny pearl detail. The smallest luxuries matter most.',
    images: [],
    stockQuantity: 60,
    isActive: true,
  },
  {
    sku: 'SL052',
    name: 'Hair Elastic / Ponytail Holder Pack',
    slug: 'hair-elastic-pack-sl052',
    price: 34,
    category: 'Ties & Elastics',
    parentCategory: 'Hair Accessories',
    description: 'A pack of sturdy, no-snag ponytail holders — your hair routine\'s unsung heroes.',
    images: [],
    stockQuantity: 55,
    isActive: true,
  },
  {
    sku: 'SL053',
    name: 'Cartoon Snap Hair Clip Set',
    slug: 'cartoon-snap-clip-set-sl053',
    price: 90,
    category: 'Kids & Novelty Sets',
    parentCategory: 'Hair Accessories',
    description: 'Adorable cartoon-themed snap clips that kids will love to wear and show off.',
    images: [],
    stockQuantity: 30,
    isActive: true,
  },
  {
    sku: 'SL054',
    name: 'Cartoon Snap Hair Clip',
    slug: 'cartoon-snap-clip-sl054',
    price: 40,
    category: 'Kids & Novelty Sets',
    parentCategory: 'Hair Accessories',
    description: 'A single cartoon snap clip — a small treat that makes a big impression on little ones.',
    images: [],
    stockQuantity: 45,
    isActive: true,
  },
  {
    sku: 'SL055',
    name: 'Striped Bow Clip',
    slug: 'striped-bow-clip-sl055',
    price: 25,
    category: 'Bows',
    parentCategory: 'Hair Accessories',
    description: 'A cheerful striped bow clip that adds a nautical, preppy charm to your hairstyle.',
    images: [],
    stockQuantity: 40,
    isActive: true,
  },
  {
    sku: 'SL056',
    name: 'Striped Bow Clip',
    slug: 'striped-bow-clip-sl056',
    price: 20,
    category: 'Bows',
    parentCategory: 'Hair Accessories',
    description: 'A mini striped bow clip in a complementary colorway — mix, stack, and style.',
    images: [],
    stockQuantity: 45,
    isActive: true,
  },
  {
    sku: 'SL057',
    name: 'Small Plaid Bow Clip Set',
    slug: 'small-plaid-bow-set-sl057',
    price: 20,
    category: 'Bows',
    parentCategory: 'Hair Accessories',
    description: 'A set of petite plaid bow clips — subtle, sweet, and perfect for layered hair looks.',
    images: [],
    stockQuantity: 40,
    isActive: true,
  },
  {
    sku: 'SL058',
    name: 'Flower Fabric Hair Clip',
    slug: 'flower-fabric-clip-sl058',
    price: 35,
    category: 'Snap & Barrette Clips',
    parentCategory: 'Hair Accessories',
    description: 'A soft fabric flower clip that brings handmade warmth to your hair accessories collection.',
    images: [],
    stockQuantity: 35,
    isActive: true,
  },
  {
    sku: 'SL059',
    name: 'Matte Duck Clip / Sectioning Clip',
    slug: 'matte-duck-clip-sl059',
    price: 34,
    category: 'Duck & Alligator Clips',
    parentCategory: 'Hair Accessories',
    description: 'A smooth matte-finish duck clip — understated, practical, and quietly stylish.',
    images: [],
    stockQuantity: 40,
    isActive: true,
  },
  {
    sku: 'SL060',
    name: 'Pearl Bead Hair Clip Set',
    slug: 'pearl-bead-clip-set-sl060',
    price: 20,
    category: 'Snap & Barrette Clips',
    parentCategory: 'Hair Accessories',
    description: 'Delicate pearl bead clips in a set — because pearls are always a good idea.',
    images: [],
    stockQuantity: 40,
    isActive: true,
  },
  {
    sku: 'SL061',
    name: 'Flower Duck Clip Set',
    slug: 'flower-duck-clip-set-sl061',
    price: 30,
    category: 'Duck & Alligator Clips',
    parentCategory: 'Hair Accessories',
    description: 'A set of flower-topped duck clips — functional sectioning clips that look garden-fresh.',
    images: [],
    stockQuantity: 35,
    isActive: true,
  },
  {
    sku: 'SL062',
    name: 'Press-on Nails',
    slug: 'press-on-nails-sl062',
    price: 150,
    category: 'Nails',
    parentCategory: 'Nails',
    description: 'Premium press-on nails with intricate designs. Salon-perfect nails in minutes, with no salon appointment needed.',
    images: [],
    stockQuantity: 20,
    isActive: true,
  },
  // SL063 — ⚠ EXCLUDED: Blank entry with #VALUE! price
  // SL064 — ⚠ EXCLUDED: Blank entry with #VALUE! price
  {
    sku: 'SL065',
    name: 'Rhinestone Butterfly Claw Clip',
    slug: 'rhinestone-butterfly-claw-sl065',
    price: 301,
    category: 'Claw Clips',
    parentCategory: 'Hair Accessories',
    description: 'A breathtaking butterfly claw clip encrusted with rhinestones. A statement piece that turns heads.',
    images: [],
    stockQuantity: 12,
    isActive: true,
  },
  {
    sku: 'SL066',
    name: 'Metal Tassel Butterfly Claw Clip',
    slug: 'metal-tassel-butterfly-claw-sl066',
    price: 175,
    category: 'Claw Clips',
    parentCategory: 'Hair Accessories',
    description: 'A metal butterfly claw clip with delicate tassel drops — movement and sparkle in one piece.',
    images: [],
    stockQuantity: 18,
    isActive: true,
  },
  {
    sku: 'SL067',
    name: 'Rhinestone Butterfly Claw Clip',
    slug: 'rhinestone-butterfly-claw-sl067',
    price: 348,
    category: 'Claw Clips',
    parentCategory: 'Hair Accessories',
    description: 'The premium edition of our rhinestone butterfly clip — larger, more stones, maximum sparkle.',
    images: [],
    stockQuantity: 10,
    isActive: true,
  },
  {
    sku: 'SL068',
    name: 'Rhinestone Bow Claw Clip',
    slug: 'rhinestone-bow-claw-sl068',
    price: 255,
    category: 'Claw Clips',
    parentCategory: 'Hair Accessories',
    description: 'A claw clip topped with a rhinestone-studded bow. Practical grip meets party-ready glamour.',
    images: [],
    stockQuantity: 15,
    isActive: true,
  },
  {
    sku: 'SL069',
    name: 'Pearl Accent Claw Clip',
    slug: 'pearl-accent-claw-sl069',
    price: 233,
    category: 'Claw Clips',
    parentCategory: 'Hair Accessories',
    description: 'A claw clip adorned with pearl accents — understated luxury for everyday wear.',
    images: [],
    stockQuantity: 18,
    isActive: true,
  },
  {
    sku: 'SL070',
    name: 'Pearl Hair Clip / Barrette',
    slug: 'pearl-barrette-sl070',
    price: 201,
    category: 'Snap & Barrette Clips',
    parentCategory: 'Hair Accessories',
    description: 'A classic pearl barrette that brings timeless elegance to any hairstyle.',
    images: [],
    stockQuantity: 15,
    isActive: true,
  },
  {
    sku: 'SL071',
    name: 'Metal Tassel Claw Clip',
    slug: 'metal-tassel-claw-sl071',
    price: 207,
    category: 'Claw Clips',
    parentCategory: 'Hair Accessories',
    description: 'A metal claw clip with swinging tassel details — adds fluid movement to your updo.',
    images: [],
    stockQuantity: 16,
    isActive: true,
  },
  {
    sku: 'SL072',
    name: 'Rhinestone & Pearl Claw Clip',
    slug: 'rhinestone-pearl-claw-sl072',
    price: 224,
    category: 'Claw Clips',
    parentCategory: 'Hair Accessories',
    description: 'The ultimate combo: rhinestone sparkle meets pearl softness in one stunning claw clip.',
    images: [],
    stockQuantity: 14,
    isActive: true,
  },
  {
    sku: 'SL073',
    name: 'Pearl Butterfly Claw Clip',
    slug: 'pearl-butterfly-claw-sl073',
    price: 301,
    category: 'Claw Clips',
    parentCategory: 'Hair Accessories',
    description: 'A butterfly claw clip wrapped in lustrous pearls — nature-inspired luxury for your hair.',
    images: [],
    stockQuantity: 12,
    isActive: true,
  },
  {
    sku: 'SL074',
    name: 'Rhinestone Flower Claw Clip',
    slug: 'rhinestone-flower-claw-sl074',
    price: 180,
    category: 'Claw Clips',
    parentCategory: 'Hair Accessories',
    description: 'A flower-shaped claw clip that catches light from every angle, thanks to precision-set rhinestones.',
    images: [],
    stockQuantity: 20,
    isActive: true,
  },
  {
    sku: 'SL075',
    name: 'Floral Headband',
    slug: 'floral-headband-sl075',
    price: 210,
    category: 'Headbands',
    parentCategory: 'Hair Accessories',
    description: 'A headband with cascading floral details — wear it to brunch, weddings, or just because you love flowers.',
    images: [],
    stockQuantity: 15,
    isActive: true,
  },
  {
    sku: 'SL076',
    name: 'Beaded Padded Headband',
    slug: 'beaded-padded-headband-sl076',
    price: 430,
    category: 'Headbands',
    parentCategory: 'Hair Accessories',
    description: 'Our most luxurious headband: fully beaded, generously padded, and designed to be the centerpiece of your outfit.',
    images: [],
    stockQuantity: 8,
    isActive: true,
  },
  {
    sku: 'SL077',
    name: 'Beaded Padded Headband',
    slug: 'beaded-padded-headband-sl077',
    price: 150,
    category: 'Headbands',
    parentCategory: 'Hair Accessories',
    description: 'A beaded padded headband at an accessible price point — same artisanal feel, lighter on the wallet.',
    images: [],
    stockQuantity: 20,
    isActive: true,
  },
  {
    sku: 'SL078',
    name: 'Beaded Padded Headband',
    slug: 'beaded-padded-headband-sl078',
    price: 101,
    category: 'Headbands',
    parentCategory: 'Hair Accessories',
    description: 'An entry-level beaded headband that proves luxury details don\'t have to come with a luxury price.',
    images: [],
    stockQuantity: 25,
    isActive: true,
  },
  {
    sku: 'SL079',
    name: 'Crystal Detail Mini Claw Clip',
    slug: 'crystal-detail-mini-claw-sl079',
    price: 270,
    category: 'Claw Clips',
    parentCategory: 'Hair Accessories',
    description: 'A mini claw clip with crystal detailing — proof that the smallest accessories can make the biggest statement.',
    images: [],
    stockQuantity: 15,
    isActive: true,
  },
];

// ─── Helper functions ───

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategorySlug(categorySlug: string): Product[] {
  const category = categories.find((c) => c.slug === categorySlug);
  if (!category) return [];
  return products.filter((p) => p.category === category.name && p.isActive);
}

export function getProductsByPriceRange(min: number, max: number): Product[] {
  return products.filter((p) => p.price >= min && p.price <= max && p.isActive);
}

export function searchProducts(query: string): Product[] {
  const q = query.toLowerCase();
  return products.filter(
    (p) =>
      p.isActive &&
      (p.name.toLowerCase().includes(q) ||
        p.category.toLowerCase().includes(q) ||
        p.sku.toLowerCase().includes(q))
  );
}

export function getRelatedProducts(product: Product, limit: number = 4): Product[] {
  return products
    .filter((p) => p.category === product.category && p.sku !== product.sku && p.isActive)
    .slice(0, limit);
}

/** Products sorted by SKU descending (newest first) — simulates "New Arrivals" */
export function getNewArrivals(limit: number = 8): Product[] {
  return [...products]
    .filter((p) => p.isActive)
    .sort((a, b) => {
      const numA = parseInt(a.sku.replace('SL', ''));
      const numB = parseInt(b.sku.replace('SL', ''));
      return numB - numA;
    })
    .slice(0, limit);
}

/** Products sorted by lowest stock (simulates "Bestsellers" — highest demand) */
export function getBestsellers(limit: number = 8): Product[] {
  return [...products]
    .filter((p) => p.isActive)
    .sort((a, b) => a.stockQuantity - b.stockQuantity)
    .slice(0, limit);
}
